### ISSUE TITLE
Dilar : اضافه رابط متعدد 

### ISSUE THREAD

**Issue by OtakuArab** [midou221/mangareader_extension#2]
ياخي الرابط الخاص بالموقع محظور في منطقتي ويوجد رابط للمصدر نفسه شغال في منطقتي هذا الرابط ياخي الذي هو شغال بمنطقتي  نتمنى اضافه خاصيه تغير روابط يدوي للمصادر اذا ممكن او يكون هناك رابط افتراضي استطيع من خلاله اضافه اي رابط لمصدر من المصادر
https://golden.rest/

**Comment by midou221** [comment]
شكرا للتنويه (تم تحديث رابط الموقع)
خلال التحديث القادم سأضيف خاصية تسمح بتغيير روابط المواقع بشكل يدوي (يفترض ان يتوفر التحديث خلال يومين)

**Comment by OtakuArab** [comment]
> شكرا للتنويه (تم تحديث رابط الموقع) خلال التحديث القادم سأضيف خاصية تسمح بتغيير روابط المواقع بشكل يدوي (يفترض ان يتوفر التحديث خلال يومين)

شكرا لك
