### ISSUE TITLE
نتمنى اضافة موقع teamx لشاي الروايات لقد اضافوا موقع خاص لروايه واحده

### ISSUE THREAD

**Issue by OtakuArab** [midou221/mangareader_extension#4]
اسم الروايه سيد الحقيقه سوى لها موقع تيم اكس موقع خاص بها فقط والفصول الجديده فيه نتمنى اضافته اذا امكن :
https://team1x1shojo.com/

**Comment by midou221** [comment]
في الوقت الحالي الأمر غير ممكن.. لكن قد اقوم بإنشاء قالب آخر يقوم بالتعرف تلقائيا على امثال هذه المواقع
شكرا لإقتراحك
