### ISSUE TITLE
نتمنى اضافه خيار لتجاوز التحقق بتطبيق شاي الرويات

### ISSUE THREAD

**Issue by OtakuArab** [midou221/mangareader_extension#5]
نتمنى اضافه خيار لتطبيق شاي الروايات لتجاوز التحقق الخاص ببعض المصادر  مثال على ذلك مصدر جنة الرويات توجد فيه هذه المشكله التحقق انني بشري

**Comment by midou221** [comment]
سأقوم بإضافة اداة لتجاوز حماية ddos
