### ISSUE TITLE
نتمنى حل هذه المشكله

### ISSUE THREAD

**Issue by OtakuArab** [midou221/mangareader_extension#7]
رابط الموقع 
https://ar.areascans.org/
ولكن شوف الخطاء
![Screenshot_٢٠٢٤٠٨٢٢-١٢١٥٤٩_ ](https://github.com/user-attachments/assets/eeffed24-0f95-4f15-86dd-ce5144415de2)

**Comment by midou221** [comment]
آآه نعم، خلل بسيط سأقوم بإصلاحه خلال التحديث القادم
شكرا على التنويه
